//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMDSystemsEntities : DbContext
    {
        public AMDSystemsEntities()
            : base("name=AMDSystemsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ip_client_custom> ip_client_custom { get; set; }
        public virtual DbSet<ip_client_notes> ip_client_notes { get; set; }
        public virtual DbSet<ip_clients> ip_clients { get; set; }
        public virtual DbSet<ip_company> ip_company { get; set; }
        public virtual DbSet<ip_company_profile> ip_company_profile { get; set; }
        public virtual DbSet<ip_custom_fields> ip_custom_fields { get; set; }
        public virtual DbSet<ip_estimate> ip_estimate { get; set; }
        public virtual DbSet<ip_estimate_items> ip_estimate_items { get; set; }
        public virtual DbSet<ip_families> ip_families { get; set; }
        public virtual DbSet<ip_import_details> ip_import_details { get; set; }
        public virtual DbSet<ip_imports> ip_imports { get; set; }
        public virtual DbSet<ip_invoice_amounts> ip_invoice_amounts { get; set; }
        public virtual DbSet<ip_invoice_custom> ip_invoice_custom { get; set; }
        public virtual DbSet<ip_invoice_groups> ip_invoice_groups { get; set; }
        public virtual DbSet<ip_invoice_item_amounts> ip_invoice_item_amounts { get; set; }
        public virtual DbSet<ip_invoice_items> ip_invoice_items { get; set; }
        public virtual DbSet<ip_invoice_tax_rates> ip_invoice_tax_rates { get; set; }
        public virtual DbSet<ip_invoices> ip_invoices { get; set; }
        public virtual DbSet<ip_invoices_recurring> ip_invoices_recurring { get; set; }
        public virtual DbSet<ip_job_portal> ip_job_portal { get; set; }
        public virtual DbSet<ip_make> ip_make { get; set; }
        public virtual DbSet<ip_merchant_responses> ip_merchant_responses { get; set; }
        public virtual DbSet<ip_model> ip_model { get; set; }
        public virtual DbSet<ip_payment_custom> ip_payment_custom { get; set; }
        public virtual DbSet<ip_payment_methods> ip_payment_methods { get; set; }
        public virtual DbSet<ip_payments> ip_payments { get; set; }
        public virtual DbSet<ip_products> ip_products { get; set; }
        public virtual DbSet<ip_projects> ip_projects { get; set; }
        public virtual DbSet<ip_purchase> ip_purchase { get; set; }
        public virtual DbSet<ip_purchase_amounts> ip_purchase_amounts { get; set; }
        public virtual DbSet<ip_purchase_custom> ip_purchase_custom { get; set; }
        public virtual DbSet<ip_purchase_item_amounts> ip_purchase_item_amounts { get; set; }
        public virtual DbSet<ip_purchase_items> ip_purchase_items { get; set; }
        public virtual DbSet<ip_purchase_tax_rates> ip_purchase_tax_rates { get; set; }
        public virtual DbSet<ip_quote_amounts> ip_quote_amounts { get; set; }
        public virtual DbSet<ip_quote_custom> ip_quote_custom { get; set; }
        public virtual DbSet<ip_quote_item_amounts> ip_quote_item_amounts { get; set; }
        public virtual DbSet<ip_quote_items> ip_quote_items { get; set; }
        public virtual DbSet<ip_quote_tax_rates> ip_quote_tax_rates { get; set; }
        public virtual DbSet<ip_quotes> ip_quotes { get; set; }
        public virtual DbSet<ip_Spares> ip_Spares { get; set; }
        public virtual DbSet<ip_tax_rates> ip_tax_rates { get; set; }
        public virtual DbSet<ip_user_clients> ip_user_clients { get; set; }
        public virtual DbSet<ip_user_custom> ip_user_custom { get; set; }
        public virtual DbSet<ip_users> ip_users { get; set; }
        public virtual DbSet<ip_versions> ip_versions { get; set; }
        public virtual DbSet<ip_email_templates> ip_email_templates { get; set; }
        public virtual DbSet<ip_item_lookups> ip_item_lookups { get; set; }
        public virtual DbSet<ip_sessions> ip_sessions { get; set; }
        public virtual DbSet<ip_settings> ip_settings { get; set; }
        public virtual DbSet<ip_tasks> ip_tasks { get; set; }
        public virtual DbSet<ip_uploads> ip_uploads { get; set; }
    }
}
