//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_custom_fields
    {
        public int custom_field_id { get; set; }
        public string custom_field_table { get; set; }
        public string custom_field_label { get; set; }
        public string custom_field_column { get; set; }
    }
}
