//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_client_notes
    {
        public int client_note_id { get; set; }
        public int client_id { get; set; }
        public System.DateTime client_note_date { get; set; }
        public string client_note { get; set; }
    
        public virtual ip_clients ip_clients { get; set; }
        public virtual ip_clients ip_clients1 { get; set; }
    }
}
