//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_company_profile
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhoneNumber { get; set; }
        public string CompanyEmailId { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyTINNumber { get; set; }
        public string Template { get; set; }
        public int Status { get; set; }
        public string SenderId { get; set; }
        public string Message { get; set; }
        public string CloseMessage { get; set; }
        public string Terms { get; set; }
        public string Prefix { get; set; }
    }
}
