//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_client_custom
    {
        public int client_custom_id { get; set; }
        public int client_id { get; set; }
    
        public virtual ip_clients ip_clients { get; set; }
        public virtual ip_clients ip_clients1 { get; set; }
        public virtual ip_clients ip_clients2 { get; set; }
        public virtual ip_clients ip_clients3 { get; set; }
        public virtual ip_clients ip_clients4 { get; set; }
        public virtual ip_clients ip_clients5 { get; set; }
        public virtual ip_clients ip_clients6 { get; set; }
        public virtual ip_clients ip_clients7 { get; set; }
        public virtual ip_clients ip_clients8 { get; set; }
    }
}
