//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_invoice_custom
    {
        public int invoice_custom_id { get; set; }
        public int invoice_id { get; set; }
        public string invoice_custom_delivery_note { get; set; }
        public string invoice_custom_delivery_date { get; set; }
        public string invoice_custom_order_no { get; set; }
        public string invoice_custom_order_date { get; set; }
    
        public virtual ip_invoices ip_invoices { get; set; }
        public virtual ip_invoices ip_invoices1 { get; set; }
    }
}
