//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_invoice_amounts
    {
        public int invoice_amount_id { get; set; }
        public int invoice_id { get; set; }
        public Nullable<decimal> invoice_item_subtotal { get; set; }
        public Nullable<decimal> invoice_item_tax_total { get; set; }
        public Nullable<decimal> invoice_tax_total { get; set; }
        public Nullable<decimal> invoice_total { get; set; }
        public Nullable<decimal> invoice_paid { get; set; }
        public Nullable<decimal> invoice_balance { get; set; }
    
        public virtual ip_invoices ip_invoices { get; set; }
        public virtual ip_invoices ip_invoices1 { get; set; }
        public virtual ip_invoices ip_invoices2 { get; set; }
    }
}
