//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_invoices_recurring
    {
        public int invoice_recurring_id { get; set; }
        public int invoice_id { get; set; }
        public System.DateTime recur_start_date { get; set; }
        public System.DateTime recur_end_date { get; set; }
        public string recur_frequency { get; set; }
        public System.DateTime recur_next_date { get; set; }
    }
}
