//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_import_details
    {
        public int import_detail_id { get; set; }
        public int import_id { get; set; }
        public string import_lang_key { get; set; }
        public string import_table_name { get; set; }
        public int import_record_id { get; set; }
    }
}
