//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_item_lookups
    {
        public int item_lookup_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public decimal item_price { get; set; }
    }
}
