//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_job_portal
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public string customer_mobile { get; set; }
        public string customer_address { get; set; }
        public string company { get; set; }
        public string job_number { get; set; }
        public System.DateTime date { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string sl_no { get; set; }
        public string gurantee { get; set; }
        public decimal paidamount { get; set; }
        public string problem { get; set; }
        public string remarks { get; set; }
        public string terms_conditions { get; set; }
        public int status { get; set; }
    }
}
