//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_merchant_responses
    {
        public int merchant_response_id { get; set; }
        public int invoice_id { get; set; }
        public System.DateTime merchant_response_date { get; set; }
        public string merchant_response_driver { get; set; }
        public string merchant_response { get; set; }
        public string merchant_response_reference { get; set; }
    }
}
