//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ip_products()
        {
            this.ip_quote_items = new HashSet<ip_quote_items>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> family_id { get; set; }
        public string product_sku { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public string provider_name { get; set; }
        public Nullable<int> tax_rate_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public string sub_cate { get; set; }
        public string serial_number { get; set; }
        public string supp_name { get; set; }
        public string warenty_detail { get; set; }
        public string selling_price { get; set; }
        public string other_info { get; set; }
        public string purchase_org_price { get; set; }
        public Nullable<bool> isdelete { get; set; }
    
        public virtual ip_families ip_families { get; set; }
        public virtual ip_tax_rates ip_tax_rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_quote_items> ip_quote_items { get; set; }
    }
}
