//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_purchase_tax_rates
    {
        public int quote_tax_rate_id { get; set; }
        public int quote_id { get; set; }
        public int tax_rate_id { get; set; }
        public int include_item_tax { get; set; }
        public Nullable<decimal> quote_tax_rate_amount { get; set; }
    }
}
