//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_quotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ip_quotes()
        {
            this.ip_payments = new HashSet<ip_payments>();
            this.ip_quote_amounts = new HashSet<ip_quote_amounts>();
            this.ip_quote_items = new HashSet<ip_quote_items>();
        }
    
        public int quote_id { get; set; }
        public int user_id { get; set; }
        public int client_id { get; set; }
        public int invoice_group_id { get; set; }
        public short quote_status_id { get; set; }
        public System.DateTime quote_date_created { get; set; }
        public System.DateTime quote_date_modified { get; set; }
        public System.DateTime quote_date_expires { get; set; }
        public string quote_number { get; set; }
        public Nullable<decimal> quote_discount_amount { get; set; }
        public Nullable<decimal> quote_discount_percent { get; set; }
        public string quote_url_key { get; set; }
        public string quote_password { get; set; }
        public string notes { get; set; }
        public int ip_quote_custom { get; set; }
        public Nullable<bool> is_quote { get; set; }
        public Nullable<int> payment_method { get; set; }
        public string delivery_notes { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string payment_notes { get; set; }
        public Nullable<bool> ispayment_completed { get; set; }
        public Nullable<bool> is_quote_delete { get; set; }
        public Nullable<bool> ispurchase { get; set; }
        public Nullable<int> taxType { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual ip_clients ip_clients { get; set; }
        public virtual ip_invoice_groups ip_invoice_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_payments> ip_payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_quote_amounts> ip_quote_amounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_quote_items> ip_quote_items { get; set; }
        public virtual ip_users ip_users { get; set; }
    }
}
