//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_quote_amounts
    {
        public int quote_amount_id { get; set; }
        public int quote_id { get; set; }
        public Nullable<decimal> quote_item_subtotal { get; set; }
        public Nullable<decimal> quote_discount { get; set; }
        public Nullable<decimal> quote_tax_total { get; set; }
        public Nullable<decimal> quote_total { get; set; }
    
        public virtual ip_quotes ip_quotes { get; set; }
    }
}
