//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_Spares
    {
        public int id { get; set; }
        public string JobId { get; set; }
        public string Spares_name { get; set; }
        public int status { get; set; }
        public decimal Amount { get; set; }
    }
}
