//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_tasks
    {
        public int task_id { get; set; }
        public string project_id { get; set; }
        public string task_name { get; set; }
        public string task_description { get; set; }
        public string task_price { get; set; }
        public string task_finish_date { get; set; }
        public string task_status { get; set; }
    }
}
