//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ip_users()
        {
            this.ip_invoices = new HashSet<ip_invoices>();
            this.ip_invoices1 = new HashSet<ip_invoices>();
            this.ip_invoices2 = new HashSet<ip_invoices>();
            this.ip_quotes = new HashSet<ip_quotes>();
        }
    
        public int user_id { get; set; }
        public int user_type { get; set; }
        public Nullable<short> user_active { get; set; }
        public System.DateTime user_date_created { get; set; }
        public System.DateTime user_date_modified { get; set; }
        public string user_name { get; set; }
        public string user_company { get; set; }
        public string user_address_1 { get; set; }
        public string user_address_2 { get; set; }
        public string user_city { get; set; }
        public string user_state { get; set; }
        public string user_zip { get; set; }
        public string user_country { get; set; }
        public string user_phone { get; set; }
        public string user_fax { get; set; }
        public string user_mobile { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_web { get; set; }
        public string user_vat_id { get; set; }
        public string user_tax_code { get; set; }
        public string user_psalt { get; set; }
        public string user_passwordreset_token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_invoices> ip_invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_invoices> ip_invoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_invoices> ip_invoices2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ip_quotes> ip_quotes { get; set; }
    }
}
