//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_uploads
    {
        public int upload_id { get; set; }
        public int client_id { get; set; }
        public string url_key { get; set; }
        public string file_name_original { get; set; }
        public string file_name_new { get; set; }
        public System.DateTime uploaded_date { get; set; }
    }
}
