//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_user_custom
    {
        public int user_custom_id { get; set; }
        public int user_id { get; set; }
        public string user_custom_bank_name { get; set; }
        public string user_custom_account_number { get; set; }
        public string user_custom_ifsc_code { get; set; }
        public string user_custom_branch { get; set; }
    }
}
