//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_versions
    {
        public int version_id { get; set; }
        public string version_date_applied { get; set; }
        public string version_file { get; set; }
        public int version_sql_errors { get; set; }
    }
}
